version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tekton-postgres
    environment:
      POSTGRES_DB: percentagedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - tekton-network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    container_name: "terton-percentage-api"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: percentagedb
      DB_USER: postgres
      DB_PASS: postgres
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - tekton-network
volumes:
  db-data:
networks:
  tekton-network:
    driver: bridge
